services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U events -d events"]
      interval: "5s"
      timeout: "5s"
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.proposed
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://events:events@db:5432/events
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata:
